### ISSUE TITLE
Credit note type code

### ISSUE THREAD

**Issue by antonio-xyz** [digipost/peppol-bis-billing-3-generator#4]
https://github.com/digipost/peppol-bis-billing-3-generator/blob/a17ffd00a62c6ebef9e7b619866d26dc998c49ca/domain/src/main/java/peppol/bis/invoice3/domain/CreditNote.java#L28

[According to Credit note type code (UNCL1001 subset)](https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL1001-cn/)
the UNCL1001 code should be 381 and not 380

**Comment by eivinhb** [comment]
I think I forgot to mention that this has been fixed.

https://github.com/digipost/peppol-bis-billing-3-generator/commit/c1f6aadaa51e8f7d7760cb0be32f35252de43dbe
